/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organisation.DoctorOrganisation;
import Business.Organisation.HealthandHumanServicesOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientDoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mitishah
 */
public class DoctorHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorHomePageJPanel
     */
//    public DoctorHomePageJPanel() {
//        initComponents();
//    }
    private JPanel userProcessContainer;
    private DoctorOrganisation organization;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    //private PatientDirectory patientDirectory;

    /**
     * Creates new form DoctorHomePageJPanel
     */
    Timer timer;
    public DoctorHomePageJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganisation organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
                        ActionListener actionlistener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
        Date date = new Date();
        DateFormat timeformat = new SimpleDateFormat("HH:mm:ss");
        String time = timeformat.format(date);
        Labtime.setText(time);
            }
        };
        timer = new Timer(1000, actionlistener);
        timer.setInitialDelay(0);
        timer.start();
        this.userProcessContainer = userProcessContainer;
        this.organization = (DoctorOrganisation)organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecoSystem = ecoSystem;
        doctorNameLable.setText(account.getName());
        populateTable();


    }
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) viewVitalSignsJTable.getModel();

        model.setRowCount(0);

        if (userAccount.getWorkQueue().getWorkRequestList() != null) {
            for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
                if (request != null) {
                    PatientDoctorWorkRequest patientDoctorWorkRequest = (PatientDoctorWorkRequest) request;
                    if (patientDoctorWorkRequest.getDoctor()== userAccount) {
                    Object[] row = new Object[7];
                    row[0] = patientDoctorWorkRequest.getDate();
                    row[1] = patientDoctorWorkRequest.getpatientName();
                    row[2] = patientDoctorWorkRequest.getisisNormal();
                    row[3] = patientDoctorWorkRequest.getFtisNormal();
                    row[4] = patientDoctorWorkRequest.getstatlab() == null ? null : patientDoctorWorkRequest.getstatlab();
                    row[5] = patientDoctorWorkRequest.getpreStat() == null ? null : patientDoctorWorkRequest.getpreStat();
                    row[6] = patientDoctorWorkRequest.getstattoRespond() == null ? null : patientDoctorWorkRequest.getstattoRespond();
                    model.addRow(row);
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBoxJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        respondJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewVitalSignsJTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        reportToGovernmentHHSDJButton = new javax.swing.JButton();
        doctorNameLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Labtime = new javax.swing.JLabel();
        Labdr = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 196, 146));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(searchBoxJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 131, -1));

        jButton1.setBackground(new java.awt.Color(230, 196, 146));
        jButton1.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jButton1.setText("Search Patient By Name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        respondJButton.setBackground(new java.awt.Color(230, 196, 146));
        respondJButton.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        respondJButton.setText("Respond To Patient");
        respondJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respondJButtonActionPerformed(evt);
            }
        });
        add(respondJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 163, -1));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("!");
        jLabel2.setEnabled(false);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 10, -1));

        jButton7.setBackground(new java.awt.Color(230, 196, 146));
        jButton7.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jButton7.setText("Make / View Prescription");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 690, -1, -1));

        jButton6.setBackground(new java.awt.Color(230, 196, 146));
        jButton6.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jButton6.setText("Request / View Test");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, 180, -1));

        viewVitalSignsJTable.setBackground(new java.awt.Color(230, 196, 146));
        viewVitalSignsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Patient Name", "Vital Signs", "Fitness", "Lab Status", "Prescription", "Respond"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewVitalSignsJTable.setSelectionBackground(new java.awt.Color(102, 255, 102));
        viewVitalSignsJTable.setSelectionForeground(new java.awt.Color(204, 0, 51));
        jScrollPane2.setViewportView(viewVitalSignsJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 900, 179));

        jButton2.setBackground(new java.awt.Color(0, 24, 91));
        jButton2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, -1, -1));

        reportToGovernmentHHSDJButton.setBackground(new java.awt.Color(230, 196, 146));
        reportToGovernmentHHSDJButton.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        reportToGovernmentHHSDJButton.setText("Report to Government Health and Human Services Department");
        reportToGovernmentHHSDJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportToGovernmentHHSDJButtonActionPerformed(evt);
            }
        });
        add(reportToGovernmentHHSDJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 750, -1, -1));

        doctorNameLable.setBackground(new java.awt.Color(0, 153, 153));
        doctorNameLable.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        doctorNameLable.setForeground(new java.awt.Color(51, 51, 51));
        doctorNameLable.setText("<doctorName>");
        doctorNameLable.setEnabled(false);
        add(doctorNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Welcome");
        jLabel1.setEnabled(false);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 24, 91));

        jLabel12.setBackground(new java.awt.Color(0, 24, 91));
        jLabel12.setFont(new java.awt.Font("Lucida Grande", 3, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MY PATIENTS LIST");
        jPanel1.add(jLabel12);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 25, 560, 50));

        jButton3.setBackground(new java.awt.Color(230, 196, 146));
        jButton3.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        jButton3.setText("Send Text Message to Patient");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 750, -1, -1));

        Labtime.setBackground(new java.awt.Color(0, 24, 91));
        Labtime.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Labtime.setForeground(new java.awt.Color(0, 24, 91));
        add(Labtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 170, 40));
        add(Labdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1030, 960));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void respondJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respondJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewVitalSignsJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);

        }

        PatientDoctorWorkRequest patientDoctorWorkRequest = (PatientDoctorWorkRequest) viewVitalSignsJTable.getValueAt(selectedRow, 0);
        patientDoctorWorkRequest.setstattoRespond("Processing");

        FitnessRecordRespondJPanel panel = new FitnessRecordRespondJPanel(userProcessContainer,enterprise,patientDoctorWorkRequest);
        userProcessContainer.add("FitnessRecordRespondJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_respondJButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewVitalSignsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);

        }else{
            PatientDoctorWorkRequest patientDoctorWorkRequest = (PatientDoctorWorkRequest)viewVitalSignsJTable.getValueAt(selectedRow, 0);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestandViewTestJPanel", new RequestandViewTestJPanel(userProcessContainer,userAccount, organization, enterprise,patientDoctorWorkRequest));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewVitalSignsJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        PatientDoctorWorkRequest patientDoctorWorkRequest = (PatientDoctorWorkRequest) viewVitalSignsJTable.getValueAt(selectedRow, 0);

        MakeAndViewPrescriptionJPanel panel = new MakeAndViewPrescriptionJPanel(userProcessContainer,userAccount,organization,enterprise,ecoSystem,patientDoctorWorkRequest);
        userProcessContainer.add("MakeAndViewPrescriptionJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void reportToGovernmentHHSDJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportToGovernmentHHSDJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewVitalSignsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);

        }else{

            PatientDoctorWorkRequest patientDoctorWorkRequest = (PatientDoctorWorkRequest)viewVitalSignsJTable.getValueAt(selectedRow, 0);

            patientDoctorWorkRequest.setSenderEnterprise(enterprise);
            patientDoctorWorkRequest.setDoctor(userAccount);

            Network targetNetwork = null;

            for (Network network : ecoSystem.getNetworkList()) {
                for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (e == enterprise) {
                        targetNetwork = network;
                        break;
                    }
                }
            }

            Organisation org = null;
            for (Enterprise e : targetNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof GovernmentEnterprise) {
                    GovernmentEnterprise emfe =(GovernmentEnterprise)e;
                    for(Organisation o:emfe.getOrganisationDirectory().getOrganizationList()){
                        if(o instanceof HealthandHumanServicesOrganisation){
                            org=o;
                            break;
                        }
                    }
                }
            }

            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(patientDoctorWorkRequest);
                //userAccount.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "Success! ");
            }

        }

    }//GEN-LAST:event_reportToGovernmentHHSDJButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MessageJPanel panel = new MessageJPanel(userProcessContainer);
        userProcessContainer.add("message", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labdr;
    private javax.swing.JLabel Labtime;
    private javax.swing.JLabel doctorNameLable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reportToGovernmentHHSDJButton;
    private javax.swing.JButton respondJButton;
    private javax.swing.JTextField searchBoxJTextField;
    private javax.swing.JTable viewVitalSignsJTable;
    // End of variables declaration//GEN-END:variables
}
