/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugSalesAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.DrugSalesOrganisation;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class DrugSalesWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugSalesWorkAreaJPanel
     */
    public DrugSalesWorkAreaJPanel() {
        initComponents();
    }
     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DrugSalesOrganisation organization;
    private EcoSystem ecoSystem;
    /**
     * Creates new form DrugSalesWorkAreaJPanel
     */
    public DrugSalesWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DrugSalesOrganisation organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = (DrugSalesOrganisation)organization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
//        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
